---
title: "HW6"
author: "Tianqi Li"
date: "2024-12-02"
output: github_document
---

```{r message = FALSE}
library(tidyverse)
```

## Problem 1

```{r message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Create the bootstrap samples

```{r}
boot_straps = 
  weather_df |>
  modelr::bootstrap(5000) |>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(tmax~tmin, data = df)),
    glance = map(models, broom::glance), 
    results = map(models, broom::tidy)
  ) |>
  unnest(glance) |>
  select(.id, r.squared, results) |>
  unnest(results) |>
  select(.id, r.squared, term, estimate) |>
  pivot_wider(names_from = term, values_from = estimate) |>
  rename(
    beta0 = `(Intercept)`,
    beta1 = tmin
  ) |>
  mutate(log = log(beta0 * beta1))
```

Plot the distribution

```{r}
boot_straps |>
  ggplot(aes(x = r.squared)) +
  geom_density() +
  ggtitle("Bootstrap Distribution of R-Squared") +
  xlab("R-Squared") +
  ylab("Frequency")

boot_straps |>
  ggplot(aes(x = log)) +
  geom_density() +
  ggtitle("Bootstrap Distribution of log(Beta0 * Beta1)") +
  xlab("log(Beta0 * Beta1)") +
  ylab("Frequency")
```

R-squared distributed between 0.87 to 0.94 with peak at about 0.915.   
log distributed between about 1.90 to 2.10 with peak about 2.02.

```{r}
boot_straps |>
  summarise(
    r2_ci_ll = quantile(r.squared, .025),
    r2_ci_ul = quantile(r.squared, .975),
    log_ci_ll = quantile(log, .025),
    log_ci_ul = quantile(log, .975)
  )
```

## Problem 2

Load the dataset
```{r message = FALSE}
data_url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide_data = read_csv(data_url)
```

Create the city_state variable and filter the dataset
```{r warning = FALSE}
homicide_df = 
  homicide_data |>
    mutate(
    city_state = paste(city, state, sep = ","),
    solved = ifelse(disposition == "Closed by arrest", 1, 0)
    ) |>
  filter(!(city_state %in% c("Dallas,TX","Phoenix,AZ","Kansas City,MO","Tulsa,AL"))) |>
  filter(victim_race %in% c("White","Black")) |>
  mutate(victim_age = as.numeric(victim_age))
```

Focus on Baltimore city
```{r}
baltimore_test <- 
  homicide_df |>
  filter(city_state == "Baltimore,MD") |>
  glm(solved ~ victim_age + victim_sex + victim_race, family = "binomial", 
      data = _) |>
  broom::tidy(conf.int = TRUE, conf.level = 0.95) |>
  mutate(
    OR = exp(estimate),
    lower = exp(conf.low),
    upper = exp(conf.high)
  ) |>
  filter(term == "victim_sexMale") |>
  select(OR, lower, upper)
baltimore_test |>
  knitr::kable(digits = 3)
```

For each cities
```{r}
city_tests <- 
  homicide_df |>
  group_by(city_state) |>
  nest() |>
  mutate(
    fit = map(
      data, ~ glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())
      ),
    results = map(fit, ~ broom::tidy(.x, conf.int = TRUE, conf.level = 0.95))
  ) |>
  unnest(results) |>
  mutate(
    OR = exp(estimate),
    lower = exp(conf.low),
    upper = exp(conf.high)
  ) |>
  filter(term == "victim_sexMale") |>
  select(city_state, OR, lower, upper)
    
city_tests |>
  knitr::kable(digits = 3)
```

Plot estimated ORs and CIs
```{r, fig.width=8, fig.height=8}
city_tests |>
  ggplot(aes(x = reorder(city_state,OR), y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, color = "darkgray") +
  labs(
    x = "City",
    y = "Odds Ratio"
  ) +
  coord_flip() +
  theme_minimal()
```

